cap_type_to_biochemical_map:
  "cap0": "m7GpppN"
  "cap1": "m7GpppNm"
  "cap2": "m7GpppNmNm"

#one letter abreviation
AminoAcids:
  "A": "Alanine"
  "R": "Arginine"
  "N": "Asparagine"
  "D": "Aspartic acid"
  "C": "Cysteine"
  "E": "Glutamic acid"
  "Q": "Glutamine"
  "G": "Glycine"
  "H": "Histidine"
  "I": "Isoleucine"
  "L": "Leucine"
  "K": "Lysine"
  "M": "Methionine"
  "F": "Phenylalanine"
  "P": "Proline"
  "S": "Serine"
  "T": "Threonine"
  "W": "Tryptophan"
  "Y": "Tyrosine"
  "V": "Valine"

# converting condos into amino acid one letter abreviation
# Start: +, Stop: -
AminoAcidTocondoMap:
  "UUU": "F"
  "UUC": "F"
  "UUA": "L"
  "UUG": "L"
  "UCU": "S"
  "UCC": "S"
  "UCA": "S"
  "UCG": "S"
  "UAU": "T"
  "UAC": "T"
  "UAA": "-"
  "UAG": "-"
  "UGU": "C"
  "UGC": "C"
  "UGA": "-"
  "UGG": "W"
  ########################
  "CUU": "L"
  "CUC": "L"
  "CUA": "L"
  "CUG": "L"
  "CCU": "P"
  "CCC": "P"
  "CCA": "P"
  "CCG": "P"
  "CAU": "H"
  "CAC": "H"
  "CAA": "Q"
  "CAG": "Q"
  "CGU": "R"
  "CGC": "R"
  "CGA": "R"
  "CGG": "R"
  ########################
  "AUU": "I"
  "AUC": "I"
  "AUA": "I"
  "AUG": "+"
  "ACU": "T"
  "ACC": "T"
  "ACA": "T"
  "ACG": "T"
  "AAU": "N"
  "AAC": "N"
  "AAA": "K"
  "AAG": "K"
  "AGU": "S"
  "AGC": "S"
  "AGA": "R"
  "AGG": "R"
  ########################
  "GUU": "V"
  "GUC": "V"
  "GUA": "V"
  "GUG": "V"
  "GCU": "A"
  "GCC": "A"
  "GCA": "A"
  "GCG": "A"
  "GAU": "D"
  "GAC": "D"
  "GAA": "E"
  "GAG": "E"
  "GGU": "G"
  "GGC": "G"
  "GGA": "G"
  "GGG": "G"